const PDFDocument = require("pdfkit");
const getStream = require("get-stream");
const axios = require("axios");

exports.handler = async (event) => {
  try {
    // Parse request body
    const { name, birthDate, birthTime, birthPlace } = JSON.parse(event.body);

    // Fetch NASA planetary data from Netlify function endpoint (live-compatible)
    let nasaData = {};
    try {
      const res = await axios.get(`/.netlify/functions/nasaKP`);
      nasaData = res.data || {};
    } catch (e) {
      nasaData = { error: "NASA data not available" };
    }

    // Create PDF
    const doc = new PDFDocument();
    doc.fontSize(20).text("Sathyadarshana KP Report", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Full Name: ${name || "N/A"}`);
    doc.text(`Birth Date: ${birthDate || "N/A"}`);
    doc.text(`Birth Time: ${birthTime || "N/A"}`);
    doc.text(`Birth Place: ${birthPlace || "N/A"}`);
    doc.moveDown();
    doc.text("Planetary Positions (NASA Data):");
    doc.text(JSON.stringify(nasaData, null, 2));
    doc.moveDown();
    doc.text("Generated by Buddhi AI", { align: "right" });

    // Convert PDF to buffer
    const buffer = await getStream.buffer(doc);

    return {
      statusCode: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="KP_Report.pdf"',
      },
      body: buffer.toString("base64"),
      isBase64Encoded: true,
    };
  } catch (err) {
    return {
      statusCode: 500,
      body: JSON.stringify({
        error: "Report generation failed",
        details: err.message,
      }),
    };
  }
};
